name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: for d in ./*/ ; do (printf "\n\nBUILD $d" && cd "$d" && go build -v -a ./cmd/...); done

    - name: Test
      run: for d in ./*/ ; do (printf "\n\nTEST $d" && cd "$d" && go test -v ./...); done
